name: "Meu Addon Compartilha Internet"
version: "1.0.0"
slug: "meu-addon-compartilha-internet"
description: "Addon para compartilhar a internet entre redes."
startup: "before_networking"
boot: "auto"
options: {}
ports: []
arch:
  - "armhf"
  - "armv7"
  - "amd64"
image: "docker.io/seu_usuario/meu-addon-compartilha-internet:latest"
host_network: true
privileged: true
devices: []
auto_uart: false
hassio_api: true
network:
  interfaces:
    - "enp2s0"
  dhcp: false
