name: Meu Addon Compartilha Internet
version: 1.3.1
slug: meu-addon-compartilha-internet
description: Addon para compartilhar a internet entre redes.
url: https://home-assistant.io/addons/dhcp_server/
codenotary: notary@home-assistant.io
arch:
  - armhf
  - armv7
  - amd64
init: false
map:
  - share:rw
options: {}
schema: {}
image: homeassistant/{arch}-addon-dhcp_server
